import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Layout from "./components/layout";
import { ConfigProvider } from "antd";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Aura Beauty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfigProvider theme={{ token: { colorPrimary: "#BC2449" } }}>
          <Layout>
            <main className="p-4 ">{children}</main>
          </Layout>
        </ConfigProvider>
      </body>
    </html>
  );
}
